name: 📘 Daily Vocabulary Update

on:
  schedule:
    - cron: "0 3 * * *"  # Runs daily at 9:00 AM IST (3:30 AM UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🔧 Set Git identity (needed before committing)
        run: |
          git config --global user.name "VanshSharmaSDE"
          git config --global user.email "vansh123321@outlook.com"  # Must match your GitHub-verified email


      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 📦 Install dependencies
        run: |
          pip install -r requirements.txt
          python -m nltk.downloader wordnet omw-1.4

      - name: 🚀 Run vocabulary generator
        run: python scripts/generate_words.py

      - name: ✅ Push all commits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
